# Generated by Django 3.1 on 2021-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0002_auto_20210207_0032'),
        ('user_extended', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_items',
            field=models.ManyToManyField(to='lemon.Item'),
        ),
    ]
