# Generated by Django 3.1 on 2021-02-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0003_delete_favouriteitem'),
        ('user_extended', '0002_profile_favourite_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_items',
            field=models.ManyToManyField(related_name='catr_items', to='lemon.Item'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_items',
            field=models.ManyToManyField(related_name='fav_items', to='lemon.Item'),
        ),
    ]
