# Generated by Django 3.1 on 2021-02-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extended', '0004_auto_20210208_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
