# Generated by Django 3.1 on 2021-02-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
