# Generated by Django 3.1 on 2021-02-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0002_auto_20210207_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteItem',
        ),
    ]
