# Generated by Django 3.1 on 2021-02-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0004_auto_20210211_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
